services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file: 
      - .env
    ports:
      - 443:443
    volumes:
      - /home/cofische/data/wordpress:/var/www/cofische
    networks:
      - frontend
    expose:
      - 9000
    #secrets:
    #  - ssl_certificate
    #  - ssl_certificate_key
    depends_on:
      - wordpress
  
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DATABASE=${DATABASE}
        - DB_ADMIN_ID=${DB_ADMIN_ID}
        - DB_ID=${DB_ID}
        - DB_HOST=${DB_HOST}
        - DOMAINE_NAME=${DOMAINE_NAME}
        - VOLUME_LOCATION=${VOLUME_LOCATION}
        - SITE_URL=${SITE_URL}
        - SITE_TITLE=${SITE_TITLE}
        - WP_ADMIN_ID=${WP_ADMIN_ID}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - WP_LOCAL=${WP_LOCAL}
    secrets:
      - db_admin_pwd
      - db_pwd
    env_file: .env   
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend
    expose:
      - 3306
    restart: always
  
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - /home/cofische/data/wordpress:/var/www/cofische    
    networks:
      - frontend
      - backend
    expose:
      - 9000
      - 3306
    depends_on:
      - mariadb

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

secrets:
  db_admin_pwd:
    file: .secrets/.db_admin_pwd.txt
  db_pwd:
    file: .secrets/.db_pwd.txt
#  ssl_certificate:
#    file: /etc/nginx/ssl/self.crt
#  ssl_certificate_key:
#    file: /etc/nginx/ssl/self.key

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/cofische/data/mariadb
      o: bind