services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file: 
      - .env
    ports:
      - 443:443
    volumes:
      - /home/cofische/data/wordpress:/var/www/cofische
    networks:
      - frontend
    expose:
      - 9000
    depends_on:
      - wordpress
  
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    user: "mysql:mysql" 
    container_name: mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - backend
    expose:
      - 3306
    restart: always
  
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - /home/cofische/data/wordpress:/var/www/cofische    
    networks:
      - frontend
      - backend
    expose:
      - 9000
      - 3306
    depends_on:
      - mariadb

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/cofische/data/mariadb
      o: bind
