services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file: 
      - .secrets/.env
    ports:
      - 443:443
    volumes:
      - /home/cofische/data/wordpress:/var/www/cofische
    networks:
      - frontend
    expose:
      - 9000
    #secrets:
    #  - ssl_certificate
    #  - ssl_certificate_key
    depends_on:
      - wordpress
  
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - /home/cofische/data/mariadb:/var/lib/mysql
    env_file: 
      - .secrets/.env
    environment:
      - DATABASE=Travel
      - DB_ADMIN_ID=InceptionMaster
      - DB_ID=RandomUser
    networks:
      - backend
    expose:
      - 3306
  
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: 
      - .secrets/.env
    volumes:
      - /home/cofische/data/wordpress:/var/www/cofische
    networks:
      - frontend
      - backend
    expose:
      - 9000
      - 3306
    depends_on:
      - mariadb

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

#secrets:
#  ssl_certificate:
#    file: /etc/nginx/ssl/self.crt
#  ssl_certificate_key:
#    file: /etc/nginx/ssl/self.key