services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file: 
      - /.secrets/.env_global
    ports:
      - 443:443
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure
  
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: /.secrets/.env_global
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception
    expose:
      - 3306
    restart: on-failure
  
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress-volume:/var/www/wordpress  
    networks:
      - inception
    expose:
      - 9000
    env_file:
      - /.secrets/.env_global
    depends_on:
      - mariadb
    restart: on-failure

  ftp-server:
    build: ./requirements/bonus/ftp-server
    image: ftp-server
    container_name: ftp_server
    volumes:
      - ftp-volume:/var/vsftpd
    networks:
      - inception
    env_file:
      - /.secrets/.env_global
    ports:
      - "21:21"
      - "21100-21200:21100-21200"
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  mariadb-volume:
    driver_opts:
      type: none
      device: /home/cofische/data/mariadb
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/cofische/data/wordpress
      o: bind
  ftp-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/cofische/data/ftp
      o: bind
