services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file: 
      - .env
    ports:
      - 443:443
    volumes:
      - wordpress-volume:/var/www/cofische
    networks:
      - inception
    expose:
      - 9000
    depends_on:
      - wordpress
  
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception
    expose:
      - 3306
    restart: on-failure
  
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress-volume:/var/www/cofische    
    networks:
      - inception
    expose:
      - 9000
    env_file:
      - ./requirements/wordpress/.env_wordpress
    depends_on:
      - mariadb
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  mariadb-volume:
    driver_opts:
      type: none
      device: /home/cofische/data/mariadb
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/cofische/data/wordpress
      o: bind
